version: "3.7"
services:

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGODB_USER=mongo
      - MONGODB_PASS=secret
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

  app:
    build: .
    container_name: api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  pgdata:
    driver: local